//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meerkat.Sitecore.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Histories = new HashSet<History>();
            this.VersionedFields = new HashSet<VersionedField>();
            this.SharedFields = new HashSet<SharedField>();
            this.UnversionedFields = new HashSet<UnversionedField>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid TemplateID { get; set; }
        public System.Guid MasterID { get; set; }
        public System.Guid ParentID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<VersionedField> VersionedFields { get; set; }
        public virtual ICollection<SharedField> SharedFields { get; set; }
        public virtual ICollection<UnversionedField> UnversionedFields { get; set; }
    }
}
