//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meerkat.Sitecore.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterEntities : DbContext
    {

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Item> Items { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<VersionedField> VersionedFields { get; set; }
        public DbSet<SharedField> SharedFields { get; set; }
        public DbSet<UnversionedField> UnversionedFields { get; set; }
    }
}
