//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meerkat.Sitecore.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnversionedField
    {
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public string Language { get; set; }
        public System.Guid FieldId { get; set; }
        public string Value { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
