//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 01/07/2014 20:40:00
namespace Meerkat.Sitecore.ItemComparer.ItemComparerService
{
    
    /// <summary>
    /// There are no comments for MasterEntities in the schema.
    /// </summary>
    public partial class MasterEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MasterEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MasterEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("IanTest_masterModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Meerkat.Sitecore.ItemComparer.ItemComparerService", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Meerkat.Sitecore.ItemComparer.ItemComparerService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("IanTest_masterModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Item> Items
        {
            get
            {
                if ((this._Items == null))
                {
                    this._Items = base.CreateQuery<Item>("Items");
                }
                return this._Items;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Item> _Items;
        /// <summary>
        /// There are no comments for Histories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<History> Histories
        {
            get
            {
                if ((this._Histories == null))
                {
                    this._Histories = base.CreateQuery<History>("Histories");
                }
                return this._Histories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<History> _Histories;
        /// <summary>
        /// There are no comments for VersionedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<VersionedField> VersionedFields
        {
            get
            {
                if ((this._VersionedFields == null))
                {
                    this._VersionedFields = base.CreateQuery<VersionedField>("VersionedFields");
                }
                return this._VersionedFields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<VersionedField> _VersionedFields;
        /// <summary>
        /// There are no comments for SharedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SharedField> SharedFields
        {
            get
            {
                if ((this._SharedFields == null))
                {
                    this._SharedFields = base.CreateQuery<SharedField>("SharedFields");
                }
                return this._SharedFields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SharedField> _SharedFields;
        /// <summary>
        /// There are no comments for UnversionedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UnversionedField> UnversionedFields
        {
            get
            {
                if ((this._UnversionedFields == null))
                {
                    this._UnversionedFields = base.CreateQuery<UnversionedField>("UnversionedFields");
                }
                return this._UnversionedFields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UnversionedField> _UnversionedFields;
        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
        /// <summary>
        /// There are no comments for Histories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHistories(History history)
        {
            base.AddObject("Histories", history);
        }
        /// <summary>
        /// There are no comments for VersionedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVersionedFields(VersionedField versionedField)
        {
            base.AddObject("VersionedFields", versionedField);
        }
        /// <summary>
        /// There are no comments for SharedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSharedFields(SharedField sharedField)
        {
            base.AddObject("SharedFields", sharedField);
        }
        /// <summary>
        /// There are no comments for UnversionedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUnversionedFields(UnversionedField unversionedField)
        {
            base.AddObject("UnversionedFields", unversionedField);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"IanTest_masterModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/" +
                "edm\"><EntityType Name=\"Item\"><Key><PropertyRef Name=\"ID\" /></Key><Property Name=" +
                "\"ID\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" /><Property " +
                "Name=\"TemplateID\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"MasterID\" T" +
                "ype=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"ParentID\" Type=\"Edm.Guid\" Null" +
                "able=\"false\" /><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" Pre" +
                "cision=\"3\" /><Property Name=\"Updated\" Type=\"Edm.DateTime\" Nullable=\"false\" Preci" +
                "sion=\"3\" /><NavigationProperty Name=\"Histories\" Relationship=\"IanTest_masterMode" +
                "l.ItemHistory\" ToRole=\"History\" FromRole=\"Item\" /><NavigationProperty Name=\"Vers" +
                "ionedFields\" Relationship=\"IanTest_masterModel.ItemVersionedField\" ToRole=\"Versi" +
                "onedField\" FromRole=\"Item\" /><NavigationProperty Name=\"SharedFields\" Relationshi" +
                "p=\"IanTest_masterModel.ItemSharedField\" ToRole=\"SharedField\" FromRole=\"Item\" /><" +
                "NavigationProperty Name=\"UnversionedFields\" Relationship=\"IanTest_masterModel.It" +
                "emUnversionedField\" ToRole=\"UnversionedField\" FromRole=\"Item\" /></EntityType><En" +
                "tityType Name=\"History\"><Key><PropertyRef Name=\"Id\" /><PropertyRef Name=\"Categor" +
                "y\" /><PropertyRef Name=\"Action\" /><PropertyRef Name=\"ItemId\" /><PropertyRef Name" +
                "=\"ItemLanguage\" /><PropertyRef Name=\"ItemVersion\" /><PropertyRef Name=\"ItemPath\"" +
                " /><PropertyRef Name=\"UserName\" /><PropertyRef Name=\"TaskStack\" /><PropertyRef N" +
                "ame=\"AdditionalInfo\" /><PropertyRef Name=\"Created\" /></Key><Property Name=\"Id\" T" +
                "ype=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Category\" Type=\"Edm.String\" Nu" +
                "llable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Property Na" +
                "me=\"Action\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false" +
                "\" Unicode=\"false\" /><Property Name=\"ItemId\" Type=\"Edm.Guid\" Nullable=\"false\" /><" +
                "Property Name=\"ItemLanguage\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" F" +
                "ixedLength=\"false\" Unicode=\"false\" /><Property Name=\"ItemVersion\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><Property Name=\"ItemPath\" Type=\"Edm.String\" Nullable=\"fals" +
                "e\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"UserName" +
                "\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"250\" FixedLength=\"false\" Unicode" +
                "=\"true\" /><Property Name=\"TaskStack\" Type=\"Edm.String\" Nullable=\"false\" MaxLengt" +
                "h=\"Max\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"AdditionalInfo\" Ty" +
                "pe=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"tr" +
                "ue\" /><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3" +
                "\" /><NavigationProperty Name=\"Item\" Relationship=\"IanTest_masterModel.ItemHistor" +
                "y\" ToRole=\"Item\" FromRole=\"History\" /></EntityType><EntityType Name=\"VersionedFi" +
                "eld\"><Key><PropertyRef Name=\"Id\" /><PropertyRef Name=\"ItemId\" /><PropertyRef Nam" +
                "e=\"FieldId\" /></Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Prop" +
                "erty Name=\"ItemId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Language\" " +
                "Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"t" +
                "rue\" /><Property Name=\"Version\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Na" +
                "me=\"FieldId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Value\" Type=\"Edm" +
                ".String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><" +
                "Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><Pr" +
                "operty Name=\"Updated\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><Navi" +
                "gationProperty Name=\"Item\" Relationship=\"IanTest_masterModel.ItemVersionedField\"" +
                " ToRole=\"Item\" FromRole=\"VersionedField\" /><NavigationProperty Name=\"ItemVersion" +
                "\" Relationship=\"IanTest_masterModel.VersionedFieldItem\" ToRole=\"Item\" FromRole=\"" +
                "VersionedField\" /></EntityType><EntityType Name=\"SharedField\"><Key><PropertyRef " +
                "Name=\"Id\" /><PropertyRef Name=\"ItemId\" /></Key><Property Name=\"Id\" Type=\"Edm.Gui" +
                "d\" Nullable=\"false\" /><Property Name=\"ItemId\" Type=\"Edm.Guid\" Nullable=\"false\" /" +
                "><Property Name=\"FieldId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Val" +
                "ue\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" Precis" +
                "ion=\"3\" /><Property Name=\"Updated\" Type=\"Edm.DateTime\" Nullable=\"false\" Precisio" +
                "n=\"3\" /><NavigationProperty Name=\"Item\" Relationship=\"IanTest_masterModel.ItemSh" +
                "aredField\" ToRole=\"Item\" FromRole=\"SharedField\" /></EntityType><EntityType Name=" +
                "\"UnversionedField\"><Key><PropertyRef Name=\"Id\" /><PropertyRef Name=\"ItemId\" /></" +
                "Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"ItemI" +
                "d\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Language\" Type=\"Edm.String" +
                "\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property" +
                " Name=\"FieldId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Value\" Type=\"" +
                "Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" />" +
                "<Property Name=\"Updated\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><N" +
                "avigationProperty Name=\"Item\" Relationship=\"IanTest_masterModel.ItemUnversionedF" +
                "ield\" ToRole=\"Item\" FromRole=\"UnversionedField\" /></EntityType><Association Name" +
                "=\"ItemHistory\"><End Type=\"IanTest_masterModel.Item\" Role=\"Item\" Multiplicity=\"1\"" +
                " /><End Type=\"IanTest_masterModel.History\" Role=\"History\" Multiplicity=\"*\" /><Re" +
                "ferentialConstraint><Principal Role=\"Item\"><PropertyRef Name=\"ID\" /></Principal>" +
                "<Dependent Role=\"History\"><PropertyRef Name=\"ItemId\" /></Dependent></Referential" +
                "Constraint></Association><Association Name=\"ItemVersionedField\"><End Type=\"IanTe" +
                "st_masterModel.Item\" Role=\"Item\" Multiplicity=\"1\" /><End Type=\"IanTest_masterMod" +
                "el.VersionedField\" Role=\"VersionedField\" Multiplicity=\"*\" /><ReferentialConstrai" +
                "nt><Principal Role=\"Item\"><PropertyRef Name=\"ID\" /></Principal><Dependent Role=\"" +
                "VersionedField\"><PropertyRef Name=\"ItemId\" /></Dependent></ReferentialConstraint" +
                "></Association><Association Name=\"ItemSharedField\"><End Type=\"IanTest_masterMode" +
                "l.Item\" Role=\"Item\" Multiplicity=\"1\" /><End Type=\"IanTest_masterModel.SharedFiel" +
                "d\" Role=\"SharedField\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=" +
                "\"Item\"><PropertyRef Name=\"ID\" /></Principal><Dependent Role=\"SharedField\"><Prope" +
                "rtyRef Name=\"ItemId\" /></Dependent></ReferentialConstraint></Association><Associ" +
                "ation Name=\"ItemUnversionedField\"><End Type=\"IanTest_masterModel.Item\" Role=\"Ite" +
                "m\" Multiplicity=\"1\" /><End Type=\"IanTest_masterModel.UnversionedField\" Role=\"Unv" +
                "ersionedField\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Item\">" +
                "<PropertyRef Name=\"ID\" /></Principal><Dependent Role=\"UnversionedField\"><Propert" +
                "yRef Name=\"ItemId\" /></Dependent></ReferentialConstraint></Association><Associat" +
                "ion Name=\"VersionedFieldItem\"><End Type=\"IanTest_masterModel.Item\" Role=\"Item\" M" +
                "ultiplicity=\"1\" /><End Type=\"IanTest_masterModel.VersionedField\" Role=\"Versioned" +
                "Field\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Item\"><Propert" +
                "yRef Name=\"ID\" /></Principal><Dependent Role=\"VersionedField\"><PropertyRef Name=" +
                "\"FieldId\" /></Dependent></ReferentialConstraint></Association></Schema><Schema N" +
                "amespace=\"Meerkat.Sitecore.Service\" xmlns=\"http://schemas.m";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "icrosoft.com/ado/2009/11/edm\"><EntityContainer Name=\"MasterEntities\" m:IsDefaultE" +
                "ntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.micr" +
                "osoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"Items\" EntityType=\"IanTes" +
                "t_masterModel.Item\" /><EntitySet Name=\"Histories\" EntityType=\"IanTest_masterMode" +
                "l.History\" /><EntitySet Name=\"VersionedFields\" EntityType=\"IanTest_masterModel.V" +
                "ersionedField\" /><EntitySet Name=\"SharedFields\" EntityType=\"IanTest_masterModel." +
                "SharedField\" /><EntitySet Name=\"UnversionedFields\" EntityType=\"IanTest_masterMod" +
                "el.UnversionedField\" /><AssociationSet Name=\"ItemHistory\" Association=\"IanTest_m" +
                "asterModel.ItemHistory\"><End Role=\"Item\" EntitySet=\"Items\" /><End Role=\"History\"" +
                " EntitySet=\"Histories\" /></AssociationSet><AssociationSet Name=\"ItemVersionedFie" +
                "ld\" Association=\"IanTest_masterModel.ItemVersionedField\"><End Role=\"Item\" Entity" +
                "Set=\"Items\" /><End Role=\"VersionedField\" EntitySet=\"VersionedFields\" /></Associa" +
                "tionSet><AssociationSet Name=\"ItemSharedField\" Association=\"IanTest_masterModel." +
                "ItemSharedField\"><End Role=\"Item\" EntitySet=\"Items\" /><End Role=\"SharedField\" En" +
                "titySet=\"SharedFields\" /></AssociationSet><AssociationSet Name=\"ItemUnversionedF" +
                "ield\" Association=\"IanTest_masterModel.ItemUnversionedField\"><End Role=\"Item\" En" +
                "titySet=\"Items\" /><End Role=\"UnversionedField\" EntitySet=\"UnversionedFields\" /><" +
                "/AssociationSet><AssociationSet Name=\"VersionedFieldItem\" Association=\"IanTest_m" +
                "asterModel.VersionedFieldItem\"><End Role=\"VersionedField\" EntitySet=\"VersionedFi" +
                "elds\" /><End Role=\"Item\" EntitySet=\"Items\" /></AssociationSet></EntityContainer>" +
                "</Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for IanTest_masterModel.Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Items")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Item : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="templateID">Initial value of TemplateID.</param>
        /// <param name="masterID">Initial value of MasterID.</param>
        /// <param name="parentID">Initial value of ParentID.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="updated">Initial value of Updated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Item CreateItem(global::System.Guid ID, string name, global::System.Guid templateID, global::System.Guid masterID, global::System.Guid parentID, global::System.DateTime created, global::System.DateTime updated)
        {
            Item item = new Item();
            item.ID = ID;
            item.Name = name;
            item.TemplateID = templateID;
            item.MasterID = masterID;
            item.ParentID = parentID;
            item.Created = created;
            item.Updated = updated;
            return item;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property TemplateID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid TemplateID
        {
            get
            {
                return this._TemplateID;
            }
            set
            {
                this.OnTemplateIDChanging(value);
                this._TemplateID = value;
                this.OnTemplateIDChanged();
                this.OnPropertyChanged("TemplateID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _TemplateID;
        partial void OnTemplateIDChanging(global::System.Guid value);
        partial void OnTemplateIDChanged();
        /// <summary>
        /// There are no comments for Property MasterID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MasterID
        {
            get
            {
                return this._MasterID;
            }
            set
            {
                this.OnMasterIDChanging(value);
                this._MasterID = value;
                this.OnMasterIDChanged();
                this.OnPropertyChanged("MasterID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MasterID;
        partial void OnMasterIDChanging(global::System.Guid value);
        partial void OnMasterIDChanged();
        /// <summary>
        /// There are no comments for Property ParentID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ParentID
        {
            get
            {
                return this._ParentID;
            }
            set
            {
                this.OnParentIDChanging(value);
                this._ParentID = value;
                this.OnParentIDChanged();
                this.OnPropertyChanged("ParentID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ParentID;
        partial void OnParentIDChanging(global::System.Guid value);
        partial void OnParentIDChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Updated
        {
            get
            {
                return this._Updated;
            }
            set
            {
                this.OnUpdatedChanging(value);
                this._Updated = value;
                this.OnUpdatedChanged();
                this.OnPropertyChanged("Updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Updated;
        partial void OnUpdatedChanging(global::System.DateTime value);
        partial void OnUpdatedChanged();
        /// <summary>
        /// There are no comments for Histories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<History> Histories
        {
            get
            {
                return this._Histories;
            }
            set
            {
                this._Histories = value;
                this.OnPropertyChanged("Histories");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<History> _Histories = new global::System.Data.Services.Client.DataServiceCollection<History>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for VersionedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<VersionedField> VersionedFields
        {
            get
            {
                return this._VersionedFields;
            }
            set
            {
                this._VersionedFields = value;
                this.OnPropertyChanged("VersionedFields");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<VersionedField> _VersionedFields = new global::System.Data.Services.Client.DataServiceCollection<VersionedField>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for SharedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SharedField> SharedFields
        {
            get
            {
                return this._SharedFields;
            }
            set
            {
                this._SharedFields = value;
                this.OnPropertyChanged("SharedFields");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SharedField> _SharedFields = new global::System.Data.Services.Client.DataServiceCollection<SharedField>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for UnversionedFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<UnversionedField> UnversionedFields
        {
            get
            {
                return this._UnversionedFields;
            }
            set
            {
                this._UnversionedFields = value;
                this.OnPropertyChanged("UnversionedFields");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<UnversionedField> _UnversionedFields = new global::System.Data.Services.Client.DataServiceCollection<UnversionedField>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IanTest_masterModel.History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// Category
    /// Action
    /// ItemId
    /// ItemLanguage
    /// ItemVersion
    /// ItemPath
    /// UserName
    /// TaskStack
    /// AdditionalInfo
    /// Created
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Histories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "Category", "Action", "ItemId", "ItemLanguage", "ItemVersion", "ItemPath", "UserName", "TaskStack", "AdditionalInfo", "Created")]
    public partial class History : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new History object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="category">Initial value of Category.</param>
        /// <param name="action">Initial value of Action.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="itemLanguage">Initial value of ItemLanguage.</param>
        /// <param name="itemVersion">Initial value of ItemVersion.</param>
        /// <param name="itemPath">Initial value of ItemPath.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="taskStack">Initial value of TaskStack.</param>
        /// <param name="additionalInfo">Initial value of AdditionalInfo.</param>
        /// <param name="created">Initial value of Created.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static History CreateHistory(global::System.Guid ID, string category, string action, global::System.Guid itemId, string itemLanguage, int itemVersion, string itemPath, string userName, string taskStack, string additionalInfo, global::System.DateTime created)
        {
            History history = new History();
            history.Id = ID;
            history.Category = category;
            history.Action = action;
            history.ItemId = itemId;
            history.ItemLanguage = itemLanguage;
            history.ItemVersion = itemVersion;
            history.ItemPath = itemPath;
            history.UserName = userName;
            history.TaskStack = taskStack;
            history.AdditionalInfo = additionalInfo;
            history.Created = created;
            return history;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property Action in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Action
        {
            get
            {
                return this._Action;
            }
            set
            {
                this.OnActionChanging(value);
                this._Action = value;
                this.OnActionChanged();
                this.OnPropertyChanged("Action");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Action;
        partial void OnActionChanging(string value);
        partial void OnActionChanged();
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this._ItemId = value;
                this.OnItemIdChanged();
                this.OnPropertyChanged("ItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ItemId;
        partial void OnItemIdChanging(global::System.Guid value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property ItemLanguage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemLanguage
        {
            get
            {
                return this._ItemLanguage;
            }
            set
            {
                this.OnItemLanguageChanging(value);
                this._ItemLanguage = value;
                this.OnItemLanguageChanged();
                this.OnPropertyChanged("ItemLanguage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemLanguage;
        partial void OnItemLanguageChanging(string value);
        partial void OnItemLanguageChanged();
        /// <summary>
        /// There are no comments for Property ItemVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ItemVersion
        {
            get
            {
                return this._ItemVersion;
            }
            set
            {
                this.OnItemVersionChanging(value);
                this._ItemVersion = value;
                this.OnItemVersionChanged();
                this.OnPropertyChanged("ItemVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ItemVersion;
        partial void OnItemVersionChanging(int value);
        partial void OnItemVersionChanged();
        /// <summary>
        /// There are no comments for Property ItemPath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemPath
        {
            get
            {
                return this._ItemPath;
            }
            set
            {
                this.OnItemPathChanging(value);
                this._ItemPath = value;
                this.OnItemPathChanged();
                this.OnPropertyChanged("ItemPath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemPath;
        partial void OnItemPathChanging(string value);
        partial void OnItemPathChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property TaskStack in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TaskStack
        {
            get
            {
                return this._TaskStack;
            }
            set
            {
                this.OnTaskStackChanging(value);
                this._TaskStack = value;
                this.OnTaskStackChanged();
                this.OnPropertyChanged("TaskStack");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TaskStack;
        partial void OnTaskStackChanging(string value);
        partial void OnTaskStackChanged();
        /// <summary>
        /// There are no comments for Property AdditionalInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AdditionalInfo
        {
            get
            {
                return this._AdditionalInfo;
            }
            set
            {
                this.OnAdditionalInfoChanging(value);
                this._AdditionalInfo = value;
                this.OnAdditionalInfoChanged();
                this.OnPropertyChanged("AdditionalInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AdditionalInfo;
        partial void OnAdditionalInfoChanging(string value);
        partial void OnAdditionalInfoChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Item Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this._Item = value;
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Item _Item;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IanTest_masterModel.VersionedField in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// ItemId
    /// FieldId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("VersionedFields")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "ItemId", "FieldId")]
    public partial class VersionedField : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VersionedField object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="language">Initial value of Language.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="fieldId">Initial value of FieldId.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="updated">Initial value of Updated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static VersionedField CreateVersionedField(global::System.Guid ID, global::System.Guid itemId, string language, int version, global::System.Guid fieldId, string value, global::System.DateTime created, global::System.DateTime updated)
        {
            VersionedField versionedField = new VersionedField();
            versionedField.Id = ID;
            versionedField.ItemId = itemId;
            versionedField.Language = language;
            versionedField.Version = version;
            versionedField.FieldId = fieldId;
            versionedField.Value = value;
            versionedField.Created = created;
            versionedField.Updated = updated;
            return versionedField;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this._ItemId = value;
                this.OnItemIdChanged();
                this.OnPropertyChanged("ItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ItemId;
        partial void OnItemIdChanging(global::System.Guid value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("Language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property FieldId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid FieldId
        {
            get
            {
                return this._FieldId;
            }
            set
            {
                this.OnFieldIdChanging(value);
                this._FieldId = value;
                this.OnFieldIdChanged();
                this.OnPropertyChanged("FieldId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _FieldId;
        partial void OnFieldIdChanging(global::System.Guid value);
        partial void OnFieldIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Updated
        {
            get
            {
                return this._Updated;
            }
            set
            {
                this.OnUpdatedChanging(value);
                this._Updated = value;
                this.OnUpdatedChanged();
                this.OnPropertyChanged("Updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Updated;
        partial void OnUpdatedChanging(global::System.DateTime value);
        partial void OnUpdatedChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Item Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this._Item = value;
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Item _Item;
        /// <summary>
        /// There are no comments for ItemVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Item ItemVersion
        {
            get
            {
                return this._ItemVersion;
            }
            set
            {
                this._ItemVersion = value;
                this.OnPropertyChanged("ItemVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Item _ItemVersion;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IanTest_masterModel.SharedField in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// ItemId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SharedFields")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "ItemId")]
    public partial class SharedField : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SharedField object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="fieldId">Initial value of FieldId.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="updated">Initial value of Updated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SharedField CreateSharedField(global::System.Guid ID, global::System.Guid itemId, global::System.Guid fieldId, string value, global::System.DateTime created, global::System.DateTime updated)
        {
            SharedField sharedField = new SharedField();
            sharedField.Id = ID;
            sharedField.ItemId = itemId;
            sharedField.FieldId = fieldId;
            sharedField.Value = value;
            sharedField.Created = created;
            sharedField.Updated = updated;
            return sharedField;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this._ItemId = value;
                this.OnItemIdChanged();
                this.OnPropertyChanged("ItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ItemId;
        partial void OnItemIdChanging(global::System.Guid value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property FieldId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid FieldId
        {
            get
            {
                return this._FieldId;
            }
            set
            {
                this.OnFieldIdChanging(value);
                this._FieldId = value;
                this.OnFieldIdChanged();
                this.OnPropertyChanged("FieldId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _FieldId;
        partial void OnFieldIdChanging(global::System.Guid value);
        partial void OnFieldIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Updated
        {
            get
            {
                return this._Updated;
            }
            set
            {
                this.OnUpdatedChanging(value);
                this._Updated = value;
                this.OnUpdatedChanged();
                this.OnPropertyChanged("Updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Updated;
        partial void OnUpdatedChanging(global::System.DateTime value);
        partial void OnUpdatedChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Item Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this._Item = value;
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Item _Item;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IanTest_masterModel.UnversionedField in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// ItemId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UnversionedFields")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "ItemId")]
    public partial class UnversionedField : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new UnversionedField object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="language">Initial value of Language.</param>
        /// <param name="fieldId">Initial value of FieldId.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="updated">Initial value of Updated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UnversionedField CreateUnversionedField(global::System.Guid ID, global::System.Guid itemId, string language, global::System.Guid fieldId, string value, global::System.DateTime created, global::System.DateTime updated)
        {
            UnversionedField unversionedField = new UnversionedField();
            unversionedField.Id = ID;
            unversionedField.ItemId = itemId;
            unversionedField.Language = language;
            unversionedField.FieldId = fieldId;
            unversionedField.Value = value;
            unversionedField.Created = created;
            unversionedField.Updated = updated;
            return unversionedField;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this._ItemId = value;
                this.OnItemIdChanged();
                this.OnPropertyChanged("ItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ItemId;
        partial void OnItemIdChanging(global::System.Guid value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("Language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property FieldId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid FieldId
        {
            get
            {
                return this._FieldId;
            }
            set
            {
                this.OnFieldIdChanging(value);
                this._FieldId = value;
                this.OnFieldIdChanged();
                this.OnPropertyChanged("FieldId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _FieldId;
        partial void OnFieldIdChanging(global::System.Guid value);
        partial void OnFieldIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Updated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Updated
        {
            get
            {
                return this._Updated;
            }
            set
            {
                this.OnUpdatedChanging(value);
                this._Updated = value;
                this.OnUpdatedChanged();
                this.OnPropertyChanged("Updated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Updated;
        partial void OnUpdatedChanging(global::System.DateTime value);
        partial void OnUpdatedChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Item Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this._Item = value;
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Item _Item;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
